return {}
-- return {
--   { "folke/noice.nvim",            enabled = false },
--   { "rcarriga/nvim-notify",        enabled = false },
--   { "nvim-neo-tree/neo-tree.nvim", enabled = false },   -- Disable Neo-tree
--   -- { "akinsho/nvim-bufferline.lua",  enabled = false },   -- Disable nvim-bufferline.lua
--   { "akinsho/bufferline.nvim",     disable = true },    --Disable bufferline
--   -- { "akinsho/bufferline.lua",      disable = true },    -- Disable nvim-bufferline.lua
--   { "nvimdev/dashboard-nvim",      enabled = false },
--   -- Disable FZF
--   { "ibhagwan/fzf-lua",            enabled = false },
--   -- { "junegunn/fzf",                 enabled = false },
--   -- { "nvim-telescope/telescope.nvim",               enabled = false },   -- Disable Telescope
--   -- { "nvim-lua/plenary.nvim",                       enabled = false },   -- Disable Plenary
--   -- { "nvim-treesitter/nvim-treesitter",             enabled = false },   -- Disable Treesitter
--   -- { "neovim/nvim-lspconfig",                       enabled = false },   -- Disable LSP Config
--   { "hrsh7th/nvim-cmp",            enabled = false }, -- Disable nvim-cmp
--   -- { "hrsh7th/cmp-buffer",                          enabled = false },   -- Disable cmp-buffer
--   -- { "hrsh7th/cmp-nvim-lsp",                        enabled = false },   -- Disable cmp-nvim-lsp
--   -- { "hrsh7th/cmp-path",                            enabled = false },   -- Disable cmp-path
--   -- { "L3MON4D3/LuaSnip",                            enabled = false },   -- Disable LuaSnip
--   -- { "saadparwaiz1/cmp_luasnip",                    enabled = false },   -- Disable cmp_luasnip
--   -- { "hrsh7th/cmp-cmdline",                         enabled = false },   -- Disable cmp-cmdline
--   -- { "nvim-treesitter/nvim-treesitter-textobjects", enabled = false },   -- Disable nvim-treesitter-textobjects
--   -- { "p00f/nvim-ts-rainbow",                        enabled = false },   -- Disable nvim-ts-rainbow
--   -- { "windwp/nvim-autopairs",                       enabled = false },   -- Disable nvim-autopairs
--   -- { "nvim-lua/plenary.nvim",                       enabled = false },   -- Disable plenary.nvim
--   -- { "nvim-treesitter/playground",                  enabled = false },   -- Disable treesitter playground
--   -- { "nvim-lint/nvim-lint",                         enabled = false },   -- Disable nvim-lint
--   -- { "lewis6991/gitsigns.nvim",                     enabled = false },   -- Disable gitsigns.nvim
--   -- { "folke/which-key.nvim",                        enabled = false },   -- Disable which-key.nvim
--   -- { "kevinhwang91/nvim-bqf",                       enabled = false },   -- Disable nvim-bqf
--   -- { "ThePrimeagen/harpoon",                        enabled = false },   -- Disable harpoon
--   -- { "williamboman/mason.nvim",                     enabled = false },   -- Disable mason.nvim
--   -- { "williamboman/mason-lspconfig.nvim",           enabled = false },   -- Disable mason-lspconfig
--   -- { "jose-elias-alvarez/null-ls.nvim",             enabled = false },   -- Disable null-ls.nvim
--   -- { "kabouzeid/nvim-lspinstall",                   enabled = false },   -- Disable nvim-lspinstall
--   -- { "nvim-lua/nvim-lspconfig",                     enabled = false },   -- Disable nvim-lspconfig
--   -- { "hoob3rt/lualine.nvim",                        enabled = false },   -- Disable lualine.nvim
--   -- { "nvim-lua/nvim-web-devicons",                  enabled = false },   -- Disable nvim-web-devicons
--   -- { "hrsh7th/vim-vsnip",                           enabled = false },   -- Disable vim-vsnip
--   -- { "junegunn/fzf.vim",                            enabled = false },   -- Disable fzf.vim
--   -- { "kyazdani42/nvim-web-devicons",                enabled = false },   -- Disable nvim-web-devicons
--   -- { "TimUntersberger/neogit",                      enabled = false },   -- Disable neogit
--   -- { "neovim/nvim-lspconfig",                       enabled = false },   -- Disable LSPConfig { "nvim-lua/plenary.nvim",                       enabled = false },   -- Disable plenary.nvim
--   -- { "petertriho/nvim-scrollbar",                   enabled = false },   -- Disable nvim-scrollbar
--   -- { "sindrets/diffview.nvim",                      enabled = false },   -- Disable diffview.nvim
--   -- { "voldikss/vim-floaterm",                       enabled = false },   -- Disable vim-floaterm
--   -- { "lewis6991/gitsigns.nvim",                     enabled = false },   -- Disable gitsigns.nvim
--   -- { "folke/zen-mode.nvim",                         enabled = false },   -- Disable zen-mode.nvim
--   -- { "folke/todo-comments.nvim",                    enabled = false },   -- Disable todo-comments.nvim
--   -- { "norcalli/nvim-colorizer.lua",                 enabled = false },   -- Disable nvim-colorizer
--   -- { "andymass/vim-matchup",                        enabled = false },   -- Disable vim-matchup
--   -- { "L3MON4D3/LuaSnip",                            enabled = false },   -- Disable LuaSnip
-- }
